- src/Deserializers/ClaimDeserializer.php
- src/Deserializers/EntityDeserializer.php
- tests/unit/Deserializers/EntityDeserializerTest.php
> Reuse existing methods

- tests/unit/Deserializers/LegacyItemDeserializerTest.php
This is some simple refactoring, required for https://github.com/wmde/WikibaseDataModel/issues/282.
> Replace deprecated Entity::addClaim

- src/Deserializers/ClaimDeserializer.php
- src/Deserializers/EntityDeserializer.php
- tests/unit/Deserializers/ClaimDeserializerTest.php
- tests/unit/Deserializers/EntityDeserializerTest.php
- tests/unit/Deserializers/LegacyEntityDeserializerTest.php
> Add missing exceptions to {Claim|Entity}Deserializer

- src/Deserializers/ClaimDeserializer.php
- src/Deserializers/EntityDeserializer.php
- src/Deserializers/LegacyClaimDeserializer.php
- src/Deserializers/LegacyEntityIdDeserializer.php
- src/Deserializers/LegacyFingerprintDeserializer.php
- src/Deserializers/LegacyItemDeserializer.php
- src/Deserializers/LegacyPropertyDeserializer.php
- src/Deserializers/LegacySiteLinkListDeserializer.php
- src/Deserializers/LegacySnakDeserializer.php
- src/Deserializers/LegacySnakListDeserializer.php
- src/Deserializers/LegacyStatementDeserializer.php
See https://github.com/wmde/WikibaseDataModelSerialization/pull/127 and https://github.com/wmde/WikibaseDataModelSerialization/pull/128.
> More specific param type hints in Deserializers

- src/Deserializers/LegacyPropertyDeserializer.php
This patch removes the private $serialization and $property variables
which don't belong to the state of the serializer. Furthermore,
it adds comments and typehints where needed.
> Don't store serialization in LegacyPropertyDeserializer

- src/Deserializers/LegacyItemDeserializer.php
This patch removes the private $serialization and $item variables
which don't belong to the state of the serializer. Furthermore,
it adds comments and typehints where needed.
> Don't store serialization in LegacyItemDeserializer

- src/Deserializers/LegacyFingerprintDeserializer.php
This patch removes the private $serialization variable which
doesn't belong to the state of the serializer. Furthermore,
it adds comments and typehints where needed.
> Don't store serialization in LegacyFingerprintDeserializer

- src/DeserializerFactory.php
- src/Deserializers/EntityDeserializer.php
- src/Deserializers/StatementDeserializer.php
Please look at the ~~4~~ 3 commits independently and tell me which are ok for you. I will remove the ones you are not ok with. Or you can just merge all of them. ;-)
> Refactor Claim and EntityDeserializer

- README.md
- composer.json
- mediawiki.php
- src/DeserializerFactory.php
- src/Deserializers/LegacyEntityIdDeserializer.php
- src/LegacyDeserializerFactory.php
- tests/integration/TestFactoryBuilder.php
- tests/unit/Deserializers/LegacyEntityIdDeserializerTest.php
- tests/unit/Deserializers/LegacyItemDeserializerTest.php
- tests/unit/Deserializers/LegacyPropertyDeserializerTest.php
This also:
- Updates the release notes
- Bumps version number in mediawiki.php
> Use DataModel 4.0 and DataModelServices 1.0

- README.md
- composer.json
- mediawiki.php
- src/DeserializerFactory.php
- src/Deserializers/LegacyEntityIdDeserializer.php
- src/LegacyDeserializerFactory.php
- tests/integration/TestFactoryBuilder.php
- tests/unit/Deserializers/LegacyEntityIdDeserializerTest.php
- tests/unit/Deserializers/LegacyItemDeserializerTest.php
- tests/unit/Deserializers/LegacyPropertyDeserializerTest.php
```
- Removing wikibase/data-model-services (1.1.0)
- Removing diff/diff (2.0.0)
- Removing wikibase/data-model-serialization (1.9.1)
- Installing wikibase/data-model-serialization (2.0.0)
```
Yeah \o/
> Removed dependence on DataModel Services

- .scrutinizer.yml
- composer.json
- phpcs.xml
- phpmd.xml
- tests/bootstrap.php
- tests/unit/Deserializers/LegacyPropertyDeserializerTest.php
I'm adding a bunch of bits and pieces we recently updated in Wikibase DataModel, DataModel Services and other components. If you think anything in this patch should be in a separate pull request, please tell me and I will split this. Thanks.
> Update PHPCS rule set to be close to WikibaseDataModel

- mediawiki-extension.json
- mediawiki.php
this also fixes the broken license link on Special:Version
> Use extension registration for MediaWiki credits

- README.md
- composer.json
- mediawiki-extension.json
> Release 2.1.0

- .travis.yml
Mostly for making this matrix identical to these:
* https://github.com/wmde/WikibaseDataModelSerialization/pull/202
* https://github.com/wmde/WikibaseDataModelServices/pull/140
> Update DataModel version matrix in .travis.yml

- .travis.yml
- composer.json
Updating the PHP version is long, long overdue.
[Bug: T165123](https://phabricator.wikimedia.org/T165123)
> Declare compatibility with data-values/geo 2.0

- .travis.yml
- README.md
- composer.json
- tests/integration/DeserializerFactoryTest.php
- tests/integration/SerializerFactoryTest.php
- tests/integration/TestFactoryBuilder.php
- tests/unit/Deserializers/EntityDeserializerTest.php
- tests/unit/Deserializers/LegacyItemDeserializerTest.php
- tests/unit/Deserializers/LegacySnakDeserializerTest.php
- tests/unit/Deserializers/LegacySnakListDeserializerTest.php
- tests/unit/Deserializers/LegacyStatementDeserializerTest.php
- tests/unit/Deserializers/StatementDeserializerTest.php
Won't know if this works until a new DataModel Serialization has been made, since it currently keeps back the DataModel version. See https://github.com/wmde/WikibaseDataModelServices/pull/198
>  Added compatibility with Wikibase DataModel 8.x 

- composer.json
- phpcs.xml
> Replace wikibase-codesniffer with mediawiki-codesniffer

- .travis.yml
- composer.json
Bug: [T271109](https://phabricator.wikimedia.org/T271109)
> Add PHP 8 to CI

- composer.json
Bug: [T188395](https://phabricator.wikimedia.org/T188395)
> Make sure all Wikibase codebases run PHPCS during `composer test`

- .travis.yml
- composer.json
> Reflect the IRC migration to libera.chat
